version: 0.2

phases:
  pre_build:
    commands:
      - echo ">> Step 1/2: Validating script permissions and deployment files..."
      - chmod +x entrypoint.sh
  build:
    commands:
      - echo ">> Step 2/2: Packaging LiveKit deployment artifacts for Elastic Beanstalk..."
      - echo "Packaging completed successfully."

artifacts:
  files:
    - Dockerfile
    - docker-compose.yml
    - entrypoint.sh
    - livekit.yaml
    - .ebextensions/**/*
  discard-paths: no
